# fly.toml file generated for jinfra-dns on 2021-05-21T19:29:44+02:00

app = "jinfra-dns"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 53
  protocol = "udp"

  [[services.ports]]
    port = 53
